export const FETCH_SHOP_ITEMS = 'FETCH_SHOP_ITEMS'

export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'

export const FETCH_PERSONAL_DATA = 'FETCH_PERSONAL_DATA'
export const UPDATE_PERSONAL_DATA = 'UPDATE_PERSONAL_DATA'
export const SET_NEWSLETTER_EMAIL = 'SET_NEWSLETTER_EMAIL'
export const REMOVE_NEWSLETTER_EMAIL = 'REMOVE_NEWSLETTER_EMAIL'

export const FETCH_ADDRESS_BOOK = 'FETCH_ADDRESS_BOOK'

export const FETCH_ORDERS = 'FETCH_ORDERS'