export const SHOP_NAME = 'Coffeeland';
export const FIRST_NAME = 'First name';
export const LAST_NAME = 'Last name';
export const EMAIL = 'Email address';
export const PASSWORD = 'Password';
export const REPEAT_PASSWORD = 'Repeat password';
export const REGISTER = 'Register';
export const SIGN_IN = 'Sign in';
export const AGREE_TO_TERMS = 'Agree to terms and conditions';
export const MY_ACCOUNT = 'My account';
export const CART = 'Cart';
export const SIGN_IN_REGISTER = 'Sign in/Register';
export const SIGN_OUT = 'Sign out';
export const SHOP = 'Buy Coffee';
export const INFORMATION = 'Information';
export const ADD_TO_CART = 'Add to cart';
export const SHOPPING_CART = 'Shopping cart';
export const BUY = 'Buy';
export const FILTER_BY_TYPE = 'Filter by type';
export const FILTER_BY_PRICE = 'Filter by price';
export const MIN_PRICE = 'Minimum price: ';
export const MAX_PRICE = 'Maximum price: ';
export const PROFILE = 'Profile'
export const NEWSLETTER = 'Newsletter'
export const ADDRESS_BOOK = 'Address book'
export const ORDERS = 'Orders'
export const EDIT = 'Edit'
export const SAVE = 'Save'
export const CANCEL = 'Cancel'
export const REMOVE = 'Remove'
export const PERSONAL_DATA = 'Personal data'
export const PROCESSING = 'Processing'
export const COMPLETED = 'Completed'
export const UNDEFINED = 'UNDEFINED' 
export const PRODUCTS = 'Products'