version: 2.1
executors:
  dotnet-executor:
    docker:
      - image: microsoft/dotnet
  nodejs-executor:
    docker:      
      - image: circleci/node:4.8.2
jobs:
  backend:
    executor: dotnet-executor
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
  frontend:
    executor: nodejs-executor
    steps:
      - checkout
      - run:
          name: update-npm 
          command: 'sudo npm install -g npm@latest'
workflows:
  version: 2.1
  build_all:
    jobs:
      - backend
      - frontend
